language: cpp
sudo: false
cache:
  directories:
  - container
matrix:
  include:
  - os: linux
    env: CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" DEPLOY="1"
  - os: linux
    env: CMAKE_GENERATOR="Ninja" CMAKE_VERSION="latest"
  - os: linux
    env: CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="3.0"
  - os: linux
    env: CMAKE_GENERATOR="Ninja" CMAKE_VERSION="3.0"
  - os: linux
    env: CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" COVERAGE="--use-cmake-coverage"
  - os: osx
    env: CMAKE_GENERATOR="Xcode" CMAKE_VERSION="latest"
env:
  global:
  - secure: adljeqAATRn9f8EsV5FLW5B2utlX/n4DzfiEnJWonjlN+Aw8vEv7MrbCbQtP3qeR4DUr/7/qVkN0fVndN/wsesmTuTD1K/G1W4BNdePuOgWxCdbbgAxDHnfJ8YxKbezXS7y9zwfCYGVkyNqcszuU8QxPUCbBP+e6QaycabAPB+g=
  - secure: QtxtzXXlr72oLovd34OOjhZXPC20qmOaCR3cNWC7EZT1ZrQBYw3yEMrAujbWVo8X7dLO3PWqmAPkD2VEwVPIdmpVRpUzbVINicDHP4uNZDovJSjB1gk0BjFWGdtQv++lV6C807TYURf/ZquvMPlwJijf15Ch3vRfc7Xjbhtd3OY=
  - secure: lawrGhhJVtBysGT/rxtpmFpC1NIGJ4oW4PUwt5XDKjOiIYa6IdczEknFwqf5RDMKL0bC58YhFnn3JB4Mg4r1xxD/SOKuLu/15ykj7bE3KI/j0NpOEFLm4GlJw1T+u5nEiPP8DY4s9PZI274pGBfFi7X/w3anjdo71x79cPHLu8I=
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.4-dev
install:
- eval $(curl -LSs --retry 100 --connect-timeout 3 public-travis-scripts.polysquare.org/bootstrap.py
  | python /dev/stdin -d container -s setup/conan/setup.py -e bash -p /dev/stdout
  --cmake-version ${CMAKE_VERSION})
script:
- polysquare_run check/conan/check.py ${COVERAGE} --cmake-namespace psq --generator
  "${CMAKE_GENERATOR}"
before_cache:
- polysquare_cleanup
after_success:
- polysquare_run coverage/cmake/coverage.py
before_deploy:
- polysquare_run deploy/conan/before_deploy.py --package="cmake-header-language"
deploy:
  provider: script
  script: "./travis-deploy"
  skip_cleanup: true
  on:
    repo: polysquare/cmake-header-language
    branch: master
    condition: "${DEPLOY} = 1"
