language: cpp
env:
  - CMAKE_GENERATOR="Unix Makefiles"
  - CMAKE_GENERATOR="Ninja"
before_install:
  - git submodule update --init --recursive
  - sudo apt-get -y purge cmake
  - sudo add-apt-repository -y ppa:kubuntu-ppa/beta
  - sudo apt-add-repository -y ppa:saiarcot895/chromium-dev
  - gem install coveralls-lcov;
  - sudo pip install cmakelint
  - sudo apt-get update -qq
  - sudo apt-get install -qq `cat DEPENDENCIES`
  - cmake --version
  # Workaround to get Ninja to display verbose output
  - if [[ $CMAKE_GENERATOR == "Ninja" ]] ; then
     echo -e '!#/bin/bash\n/usr/bin/ninja -v $@' > ninja;
     chmod +x ninja;
     export PATH=`pwd`:${PATH};
    fi
script:
  - mkdir -p test/build
  - pushd test/build
  - cmake .. -G "${CMAKE_GENERATOR}" -DCMAKE_UNIT_LOG_COVERAGE=1
  - ctest --output-on-failure
  - popd
  # Find all errors except:
  # 1. Spaces between control and condition (preferred style)
  # 2. Indentation errors
  - find . -type f -name "*.cmake" -not -path "./test/build/*"| xargs cmakelint --spaces=4 --filter=-whitespace/extra,-whitespace/indent > .cmake-lint-log
  - cat .cmake-lint-log
  # Fails if file has length
  - echo "! [ -s .cmake-lint-log ]" > .check-link-script.bash
  - bash .check-link-script.bash
after_success:
  - cmake -DTRACEFILE=test/build/PolysquareCMakeHeaderLanguageTests.trace -DLCOV_OUTPUT=test/build/coverage.info -P cmake-unit/CMakeTraceToLCov.cmake
  - coveralls-lcov test/build/coverage.info
  - popd
